# Lecture 5

## References

* Numerical Python: Scientific Computing and Data Science Applications with Numpy, SciPy and Matplotlib (2nd Edition), Robert Johansson.

## This Lecture
Continue on:
*    Vectors, Matrices and Multidimensional Arrays  
*   Numpy arrays and functions

In [1]:
import numpy as np

In [2]:
A=np.reshape(np.arange(1,37),(6,6))

In [3]:
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

## View: 

In [4]:
B=A[1:5,1:5]

In [5]:
B

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [6]:
B[:,:]=0

In [7]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [8]:
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  0,  0,  0,  0, 12],
       [13,  0,  0,  0,  0, 18],
       [19,  0,  0,  0,  0, 24],
       [25,  0,  0,  0,  0, 30],
       [31, 32, 33, 34, 35, 36]])

**note**: assign new values to the elements of B, which is created from the array A, also modifies the values in A

## Copy:
When a copy rather than a view is needed, we use the copy method

In [9]:
A=np.reshape(np.arange(1,37),(6,6))

In [10]:
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [11]:
B=A[1:5,1:5].copy()

In [12]:
B

array([[ 8,  9, 10, 11],
       [14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29]])

In [13]:
B[:,:]=0  # this time, changes in B does not affect A

In [14]:
B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

## Vectorized Expression

Enable batch operations on all the elements in the array

**Arithmetic Operations**

In [16]:
x=np.array([[1,2],[3,4]])

In [17]:
y=np.array([[5,6],[7,8]])

In [18]:
x

array([[1, 2],
       [3, 4]])

In [19]:
y

array([[5, 6],
       [7, 8]])

Operate on all the elements of the arrays:

In [20]:
x+y # add all the elements at one time

array([[ 6,  8],
       [10, 12]])

In [21]:
y-x

array([[4, 4],
       [4, 4]])

In [22]:
x*y  

array([[ 5, 12],
       [21, 32]])

In [23]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [24]:
x*2

array([[2, 4],
       [6, 8]])

In [25]:
x**2

array([[ 1,  4],
       [ 9, 16]])

Operators for elementwise arithmatic

|operator | Operation|
|---|---|
|+ | Addition|
|- | Subtraction|
|* | multiplication|
|/ | divisision|
|**| Exponentiation|


## Elementwise Functions

In [26]:
x=np.linspace(0,10,11)

In [27]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
y=np.sin(x)

In [29]:
y

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [30]:
np.cos(x)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

Summarize elementwise functions in numpy

|NumPy Function | Description |
|---|---|
|np.sin, np.cos, np.tan, etc. | trig functions|
|np.arcsin,np.arccos,np.arctan, etc. | inverse trig functions|
|np.cosh,np.sinh,np.tanh | hyperbolic tric| 
|np.sqrt | square root|
|np.exp | exponential|
|np.log,np.log2,np.log10 | log functions |

In [31]:
np.arcsin(np.linspace(-1,1,10))

array([-1.57079633, -0.89112251, -0.58903097, -0.33983691, -0.11134101,
        0.11134101,  0.33983691,  0.58903097,  0.89112251,  1.57079633])

In [32]:
np.sqrt(x)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

## Agregate Functions

In [33]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [34]:
x.sum()

55.0

In [35]:
x.mean()

5.0

In [36]:
np.sum(x)

55.0

In [37]:
np.mean(x)

5.0

Summarize the numpy aggregate functions

|NumPy Functions | Descriptions |
| --- | ---| 
| np.mean | average of the array |
|np. std | standard derivations| 
|np.var | variance |
|np.sum | sum of all the elementds|
|np.prod | producti of all the elements|
|np.min, np.max | minimun,  maximum of all the elements|
|np.all  | return True if all the elements is nonzero|
|np.any  | return True if any of the elements in nonzero|

In [38]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [39]:
np.prod(x)

0.0

In [40]:
np.max(x)

10.0

In [41]:
np.min(x)

0.0

In [42]:
np.any(x)

True

In [43]:
np.all(x)

False

## Matrix and Vector Operations

| NumPy Functions | Descriptions |
| --- | --- |
|np.dot | dot product between two given arrays (math matrix multiplaction)|
|np.inner | inner product between two vectors| 
|np.kron | Kronecker product of two matrices |

x=np.linspace(1,11,11)

In [44]:
y=2*x

In [45]:
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [46]:
y

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [47]:
np.dot(x,y)

770.0

In [48]:
A=np.arange(1,7).reshape(2,3)

In [49]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
B=np.arange(1,7).reshape(3,2)

In [51]:
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
np.dot(A,B)

array([[22, 28],
       [49, 64]])

Conditional and Logical Expression 

|Function | Description|
| --- | ---|
|np.where |  returns indices where condition is satisfied|
|np.nonzero | returns indices where element is nonzero|

In [53]:
x = np.linspace(-4,4,9)

In [54]:
x

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [55]:
np.where(x<0)

(array([0, 1, 2, 3]),)

In [56]:
np.nonzero(x)

(array([0, 1, 2, 3, 5, 6, 7, 8]),)